# Generated by Django 4.2.9 on 2024-01-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_email_member_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_book',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='id_borrow',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='id_member',
            new_name='id',
        ),
    ]
