# Generated by Django 4.2.9 on 2024-01-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_book_bookid_member_idcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookId',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='idCard',
            new_name='id_card',
        ),
    ]
